### ISSUE TITLE
Should expand?

### ISSUE THREAD

**Issue by ZachariBarnes** [Rfrixy/Generic-Unity-Object-Pooler#1]
How Is "Should Expand" supposed to work. In my current project if the Pooler runs out of objects it just starts throwing exceptions. I would expect it to create new objects on the fly and add them into the pool.

**Comment by Rfrixy** [comment]
Setting should expand to true does do exactly that. 

Can you confirm that it is working fine till the number of objects in amountToPool?

Also, please let me know the unity version you are working with.

**Comment by ZachariBarnes** [comment]
I ran a thorough test last night and it looks like I have a race condition that is orphaning some pooled objects
 My bad. Sorry for opening the issue.

**Comment by Rfrixy** [comment]
No problem
Good luck with your game.

**Comment by ZachariBarnes** [comment]
Thanks
